name: Check Render Deployment Status

on:
  push:
    branches:
      - main 
  workflow_dispatch: 

jobs:
  check_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Wait for Deployment to Complete
        id: fetch_deploy
        run: |
          API_URL="https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys"
          MAX_RETRIES=60 
          COUNT=0

          while [ "$COUNT" -lt "$MAX_RETRIES" ]; do
            echo "Checking deployment status..."
            LATEST_DEPLOY=$(curl -s -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" $API_URL | jq -r '.[0].deploy')
            
            DEPLOY_ID=$(echo "$LATEST_DEPLOY" | jq -r '.id')
            COMMIT_ID=$(echo "$LATEST_DEPLOY" | jq -r '.commit.id')
            DEPLOY_STATUS=$(echo "$LATEST_DEPLOY" | jq -r '.status')

            echo "Deployment ID: $DEPLOY_ID"
            echo "Commit ID: $COMMIT_ID"
            echo "Current Status: $DEPLOY_STATUS"

            if [ "$DEPLOY_STATUS" == "live" ] || [ "$DEPLOY_STATUS" == "failed" ]; then
              echo "DEPLOY_STATUS=$DEPLOY_STATUS" >> $GITHUB_ENV
              echo "COMMIT_ID=$COMMIT_ID" >> $GITHUB_ENV
              echo "Deployment finished with status: $DEPLOY_STATUS"
              exit 0
            fi

            echo "Deployment is still in progress... Waiting 10 seconds"
            sleep 10
            COUNT=$((COUNT+1))
          done

          
          echo "Deployment timeout reached!"
          echo "DEPLOY_STATUS=timeout" >> $GITHUB_ENV
          exit 1

      - name: Update GitHub Commit Status
        run: |
          STATUS="pending"
          if [ "$DEPLOY_STATUS" == "live" ]; then
            STATUS="success"
          elif [ "$DEPLOY_STATUS" == "failed" ]; then
            STATUS="failure"
          elif [ "$DEPLOY_STATUS" == "timeout" ]; then
            STATUS="error"
          fi

          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/meckbaig/smart-yt-subscriptions/statuses/$COMMIT_ID \
            -d "{\"state\": \"$STATUS\", \"target_url\": \"https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys/$DEPLOY_ID\", \"description\": \"Render deployment status: $DEPLOY_STATUS\", \"context\": \"Render Deployment\"}"
