name: Check Render Deployment Status

on:
  push:
    branches:
      - main 
  workflow_dispatch: 

jobs:
  check_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Wait for Deployment to Complete
        id: fetch_deploy
        run: |
          API_URL="https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys"
          MAX_RETRIES=30 
          COUNT=0

          while [ "$COUNT" -lt "$MAX_RETRIES" ]; do
            echo "Checking deployment status..."
            RESPONSE=$(curl -s -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" $API_URL)

            if [ $? -ne 0 ] || [ -z "$RESPONSE" ]; then
              echo "Error: Failed to fetch deployment status from Render API!"
              exit 1
            fi

            LATEST_DEPLOY=$(echo "$RESPONSE" | jq -r '.[0].deploy')
            
            DEPLOY_ID=$(echo "$LATEST_DEPLOY" | jq -r '.id')
            COMMIT_ID=$(echo "$LATEST_DEPLOY" | jq -r '.commit.id')
            DEPLOY_STATUS=$(echo "$LATEST_DEPLOY" | jq -r '.status')

            if [ "$COUNT" = 0 ]; then
              echo "Deployment ID: $DEPLOY_ID"
              echo "Commit ID: $COMMIT_ID"
              echo "Current Status: $DEPLOY_STATUS"
            fi

            if [ "$DEPLOY_STATUS" == "live" ]; then
              echo "Deployment successful!"
              exit 0
            elif [ "$DEPLOY_STATUS" == "build_failed" ]; then
              echo "Deployment failed!"
              exit 1
            fi

            echo "Deployment is still in progress... Waiting 10 seconds"
            sleep 10
            COUNT=$((COUNT+1))
          done

          
          echo "Deployment timeout reached!"
          echo "DEPLOY_STATUS=timeout" >> $GITHUB_ENV
          exit 1
